name: muzika
description: A music search and download app powered by YouTube.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # YouTube search + stream extraction
  youtube_explode_dart: ^2.3.6

  # File system paths (no permissions needed with getExternalStorageDirectory)
  path_provider: ^2.1.1

  # HTTP client
  http: ^1.2.0

  # Cached network images (for thumbnails)
  cached_network_image: ^3.3.1
  permission_handler: ^12.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true